import { CourseType } from "@/types/CourseType";

export const coursesData: CourseType[] = [
  {
    _id: "course-1",
    title: "Complete React Developer Course",
    shortDescription: "Learn React from basics to advanced with real-world projects.",
    thumbnail: "/images/courses/img-1.png",
    instructor: {
      name: "John Doe",
    },
    totalLearners: 1200,
    isCertificationProvide: true,
    price: 120,
    discountPrice: 79,
    status: "Ongoing",
    slug: { current: "complete-react-developer" },
    level: "Beginner to Advanced",
    overview: [],
    duration: 120,
    lessonsCount: 24,
  },
  {
    _id: "course-2",
    title: "Next.js Full Stack Bootcamp",
    shortDescription: "Build full-stack applications using Next.js and modern tools.",
    thumbnail: "/images/courses/img-2.png",
    instructor: {
      name: "Sarah Ahmed",
    },
    totalLearners: 850,
    isCertificationProvide: true,
    price: 150,
    discountPrice: 99,
    status: "Ongoing",
    slug: { current: "nextjs-fullstack-bootcamp" },
    level: "Intermediate",
    overview: [],
    duration: 180,
    lessonsCount: 30,
  },
  {
    _id: "course-3",
    title: "JavaScript Mastery",
    shortDescription: "Master core JavaScript concepts and advanced patterns.",
    thumbnail: "/images/courses/img-3.png",
    instructor: {
      name: "Michael Lee",
    },
    totalLearners: 2000,
    isCertificationProvide: true,
    price: 100,
    discountPrice: 69,
    status: "Completed",
    slug: { current: "javascript-mastery" },
    level: "Beginner",
    overview: [],
    duration: 200,
    lessonsCount: 28,
  },
  {
    _id: "course-4",
    title: "UI/UX Design Fundamentals",
    shortDescription: "Learn the basics of UI/UX design and Figma workflows.",
    thumbnail: "/images/courses/img-4.png",
    instructor: {
      name: "Emily Carter",
    },
    totalLearners: 640,
    isCertificationProvide: false,
    price: 80,
    discountPrice: 49,
    status: "Completed",
    slug: { current: "ui-ux-design-fundamentals" },
    level: "Beginner",
    overview: [],
    duration: 190,
    lessonsCount: 26,
  },
  {
    _id: "course-5",
    title: "Node.js & Express API Development",
    shortDescription: "Build scalable backend APIs using Node.js and Express.",
    thumbnail: "/images/courses/img-5.png",
    instructor: {
      name: "David Kim",
    },
    totalLearners: 950,
    isCertificationProvide: true,
    price: 110,
    discountPrice: 75,
    status: "Ongoing",
    slug: { current: "node-express-api" },
    level: "Intermediate",
    overview: [],
    duration: 300,
    lessonsCount: 58,
  },
  {
    _id: "course-6",
    title: "Digital Marketing Complete Guide",
    shortDescription: "Learn SEO, social media marketing, and paid ads strategies.",
    thumbnail: "/images/courses/img-6.png",
    instructor: {
      name: "Nusrat Jahan",
    },
    totalLearners: 720,
    isCertificationProvide: true,
    price: 90,
    discountPrice: 59,
    status: "Completed",
    slug: { current: "digital-marketing-guide" },
    level: "Beginner",
    overview: [],
    duration: 120,
    lessonsCount: 24,
  },
];
